FROM eclipse-temurin:21-jre-jammy
WORKDIR /app

COPY build/quarkus-app/lib/ /app/lib/
COPY build/quarkus-app/app/ /app/app/
COPY build/quarkus-app/quarkus/ /app/quarkus/
COPY build/quarkus-app/quarkus-run.jar /app/

EXPOSE 8080
CMD ["java", "-Dquarkus.http.host=0.0.0.0", "-jar", "quarkus-run.jar"]
