package st.gulik;

import io.quarkus.hibernate.orm.panache.PanacheEntityBase;
import jakarta.persistence.*;

//The above Entity maps to the "url_mappings" table in the database.
@Entity
@Table(name = "url_mappings")
public class UrlMapping extends PanacheEntityBase {

    //The primary key automatically generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Long id;


    @Column(unique = true, nullable = false, length = 10)
    public String shortKey;

    @Column(nullable = false, length = 2048)
    public String originalUrl;

}

